# Generated by Django 4.2 on 2023-04-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_car_type_alter_car_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.IntegerField(choices=[(1, 'Sedan'), (2, 'Universal'), (3, 'Hatchback')], verbose_name='Car_Type'),
        ),
    ]
