# Generated by Django 4.2 on 2023-04-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_car_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.IntegerField(choices=[(3, 'Hatchback'), (1, 'Sedan'), (2, 'Universal')], verbose_name='Car_Type'),
        ),
    ]
